#!/bin/bash
# ===========================================================
# This script creates the en_US.txt file from the extension
# javascript files containing GetText
# ===========================================================

root_dir=${PWD}
files_dir=$root_dir/workspaces-to-dock@remi.cohenscali.net
output=$root_dir/po/en_US.txt
cd "$files_dir/"
xgettext -o "$output" *.js
